version: 2
jobs:
  b1:
    macos:
      xcode: 8.2.1
    steps:
      - run: ~/Library/Preferences/com.apple.dt.Xcode.plist
  b2:
    macos:
      xcode: 9.0.0
    steps:
      - run: ~/Library/Preferences/com.apple.dt.Xcode.plist

workflows:
  version: 2
  test_all:
    jobs:
      - b1
      - b2
