version: 2
jobs:
  b2:
    docker:
      - image: ruby:latest
    steps:
      - run: echo "Helllllooo"
  b1:
    macos:
      xcode: 8.2.1
    steps:
      - run: echo "Hello!"

workflows:
  version: 2
  test_all:
    jobs:
      - b2
      - b1
